// Adapted from flyfy1/integ-games c2a3374; see apps/integ-ar/README.md.
import type { GameController, GameModule, GameServices } from '../../core/game-types';
import { makeKit, text } from '../arcade-kit';

export const knife: GameModule = { meta: { slug: 'knife', title: 'Orbit Knife', category: 'arcade', description: 'Thread throws through a spinning neon core.', instructions: 'Tap or press Space to throw; avoid knives already embedded.', accent: '#ff6b7a', mechanic: 'Time throws without collisions' }, mount(host: HTMLElement, services: GameServices): GameController {
  const k = makeKit(host, services, 'knife', 360, 520); let raf = 0, paused = false, over = false, score = 0, rotation = 0, stuck: number[] = [], flying = -1, targets = 8, throws = 0;
  const reset = () => { paused = false; over = false; score = 0; rotation = 0; stuck = []; flying = -1; targets = 8; throws = 0; k.fx.clear(); };
  const throwKnife = () => { if (!paused && !over && flying < 0) { throws++; flying = 470; k.fx.burst(180, 490, '#f7f9ff', 4); services.sound.play('shoot'); } };
  reset(); k.on('pointerdown', () => over ? reset() : throwKnife()); k.on('keydown', event => { if ((event as KeyboardEvent).key === ' ') over ? reset() : throwKnife(); });
  const draw = () => { const c = k.ctx; k.clear();  text(c, `THROWS ${score} / ${targets}`, 180, 28, 15, '#a8b1c5'); c.save(); c.translate(180, 205); c.rotate(rotation); c.fillStyle = '#8b7cff'; c.beginPath(); c.arc(0, 0, 73, 0, 7); c.fill(); c.fillStyle = '#d7d1ff'; c.beginPath(); c.arc(0, 0, 13, 0, 7); c.fill(); stuck.forEach(angle => { c.save(); c.rotate(angle); c.fillStyle = '#f7f9ff'; c.fillRect(-3, -118, 6, 48); c.fillStyle = '#ff6b7a'; c.fillRect(-8, -75, 16, 7); c.restore(); }); c.restore(); if (flying >= 0) { c.globalAlpha = .2; c.fillStyle = '#ff6b7a'; c.fillRect(178, flying + 44, 4, Math.min(88, 520 - flying)); c.globalAlpha = 1; c.fillStyle = '#f7f9ff'; c.fillRect(177, flying, 6, 46); c.fillStyle = '#ff6b7a'; c.fillRect(172, flying + 39, 16, 7); } k.fx.draw(); if (paused) text(c, 'PAUSED', 180, 300, 27); if (over) { text(c, 'KNIVES CLASHED', 180, 310, 24, '#ff6b7a'); text(c, 'Finish or start a new round', 180, 340, 15); } };
  let lastStep = performance.now(); const loop = (now = lastStep) => { if (now - lastStep < 1000 / 60 - .1) { raf = requestAnimationFrame(loop); return; } lastStep = now - (now - lastStep) % (1000 / 60); if (!paused && !over) { rotation += .018 + score * .0006; if (flying >= 0) { flying -= 9; if (flying < 278) { const angle = ((Math.PI / 2 - rotation) % (Math.PI * 2) + Math.PI * 2) % (Math.PI * 2); if (stuck.some(existing => Math.abs(Math.atan2(Math.sin(angle - existing), Math.cos(angle - existing))) < .25)) { over = true; flying = -1; k.fx.flash('#ff6b7a'); services.sound.play('fail'); } else { stuck.push(angle); flying = -1; score++; k.score(score); k.fx.burst(180, 278, '#f7f9ff', 8); services.sound.play('hit'); if (score >= targets) { targets += 3; score = 0; stuck = []; services.reportComplete(targets - 8); k.fx.flash('#8b7cff'); services.sound.play('clear'); } } } } k.fx.step(); } draw(); raf = requestAnimationFrame(loop); };
  loop(); return { input: command => { if (!paused && !over && command.primary) throwKnife(); }, getState: () => ({phase: over ? 'lost' : paused ? 'paused' : 'playing', score, targets, flying, rotation, throws}), pause: () => { paused = true; }, resume: () => { paused = false; }, restart: reset, destroy: () => { cancelAnimationFrame(raf); k.dispose(); } };
} };
export default knife;
