// Player instructions follow the existing recognizers; diagrams are mirrored views.
const bodySetup='Place your camera so your shoulders, hips and hands stay in view. Enable the camera, stand still with both hands down, and complete calibration. Raise both hands above your shoulders for one second, then lower them to start.';
const bodyPause='Hold both hands above your shoulders for one second to pause or resume. Lower your hands between commands. Tracking loss pauses the game; return to view and choose Resume.';
const raise='Raise your left wrist above your left shoulder, then lower it below your shoulder before the next action. Holding it up triggers only once.';
const guide=(goal,setup,steps,tiles,pause=bodyPause)=>({goal,setup,steps,tiles,pause});
export const gameGuides={
 'ar-breakout':guide('Keep the ball in play and clear the bricks.',bodySetup,[['Move the paddle','Shift your whole torso left or right. The paddle follows the direction you see in the mirrored camera.'],['Meet the ball','Move under the falling ball to bounce it back toward the bricks. No raised-hand action is needed.'],['Finish your round','Keep returning the ball, or choose Finish round to save your replay.']],[['stand','Stand centered'],['sway','Move left / right'],['paddle','Return the ball']]),
 'ar-invaders':guide('Shoot the invaders before they reach your ship.',bodySetup,[['Steer your ship','Shift your torso left or right to line up with an invader and avoid incoming shots.'],['Fire once',raise],['Fire again','Lower your left hand fully, then raise it again for the next shot. Keep your right hand down while firing.']],[['sway','Steer with your torso'],['raise','Raise LEFT to fire'],['lower','Lower to reload']]),
 'ar-stack':guide('Build a tower by dropping each moving slab onto the one below.',bodySetup,[['Watch the moving slab','Keep your body centered and your left hand lowered while the slab slides sideways.'],['Choose the moment','Raise your left hand as the slab lines up with the tower. Your movement takes a short moment to register, so watch the timing.'],['Reset for the next slab',raise+' A missed landing ends the round.']],[['stand','Watch the alignment'],['raise','Raise LEFT to drop'],['stack','Stack the next slab']]),
 'ar-knife':guide('Throw knives into clear spaces on the rotating target.',bodySetup,[['Watch the rotation','Keep your left hand down and wait for a gap between the knives already in the target.'],['Throw into a gap',raise],['Avoid existing knives','Time the next raise for another clear space. A knife hitting another knife ends the round.']],[['stand','Wait for a gap'],['raise','Raise LEFT to throw'],['knife','Hit a clear space']]),
 'ar-bubble':guide('Match three or more bubbles of the same color to clear them.',bodySetup,[['Aim with your right wrist','Move your right wrist left, right, up or down while keeping it below shoulder height. Follow the on-screen aiming line.'],['Shoot with your left hand',raise+' Keep your right wrist below your shoulder while shooting.'],['Match colors','Aim toward matching bubbles, lower your left hand, then raise it again for the next shot. Raising both hands is reserved for pause.']],[['aim','RIGHT wrist aims'],['raise','LEFT hand shoots'],['bubble','Match the colors']]),
 'ar-fruit':guide('Drop matching fruit together to merge them into larger fruit.',bodySetup,[['Choose a drop position','Shift your torso left or right. The held fruit follows your movement across the container.'],['Release the fruit',raise],['Plan the next drop','Let the fruit settle and place matching fruit together. Keep the pile below the top boundary.']],[['sway','Choose a position'],['raise','Raise LEFT to drop'],['fruit','Merge matching fruit']]),
 'motion-quest':guide('Complete five squat-and-stand actions to defeat the forest guardian.','Enable the camera, keep shoulders through ankles visible, turn slightly sideways and stand upright for about two seconds to calibrate.',[['Charge your spell','Bend your knees into a comfortable squat. Watch the charge indicator fill.'],['Cast the spell','Stand upright again to complete the action and attack. Staying crouched does not score another repetition.'],['Repeat five times','Return to standing between repetitions. The round ends after five completed actions.']],[['stand','Stand to calibrate'],['squat','Squat to charge'],['stand-up','Stand to cast']],'Use the game’s Stop control to end camera play. If tracking is lost, return to view before continuing.'),
 'plank-flight':guide('Guide the helicopter through the openings between gates.','Position your camera so your head and at least one shoulder are visible in a comfortable push-up position. Enable the camera and hold in view for the automatic countdown.',[['Move your head','The helicopter follows your head in the mirrored camera: move up, down or sideways to steer.'],['Pass through the gates','Lower and push up at your own pace to line up with the next opening. Gate opening and speed can be adjusted in the game.'],['Finish and rest','Choose Finish & rest when you want to stop. Try a demo uses pointer or arrow-key controls without a camera.']],[['pushup','Head + shoulder visible'],['head','Move your head'],['flight','Fly through gates']],'Use Finish & rest to end a flight. The camera stops if the page is hidden or loses focus.'),
 'jump-game':guide('Raise and return your body to help Dino clear the cacti.','Enable the camera and stand still to calibrate. Raise your LEFT hand above your shoulder for one second with your right hand down, or select Confirm & continue. Then follow the three-second countdown.',[['Confirm your standing pose','Stand still while your movement range is set automatically, then raise your LEFT hand for one second or select Confirm & continue. No calibration jump is required.'],['Clear an obstacle','Raise your body as a cactus approaches, then return to your standing position. Dino turns the detected rise and return into a jump.'],['Reset between jumps','Return to your baseline before the next movement. Keep your shoulders and hips visible.']],[['stand','Set your standing pose'],['jump','Rise, then return'],['dino','Clear the cactus']]),
 'dino-run':guide('Help Dino jump over the cacti.','Enable the camera, calibrate standing and a comfortable jump range, then raise one hand for one second to confirm. Lower both hands before the countdown.',[['Calibrate first','Keep your shoulders and hips visible and follow the standing and jump-range prompts.'],['Lift Dino','Raise your torso to lift Dino. Your return toward standing brings Dino back down.'],['Time the next rise','Return to your standing baseline between obstacles. The displayed height is relative to your own calibration.']],[['stand','Calibrate standing'],['jump','Raise your torso'],['dino','Clear the cactus']]),
 'dino-ar':guide('Jump Dino through the obstacles over your live camera view.','Choose camera play, keep your shoulders and hips visible, and follow the standing calibration prompts.',[['Stand in view','Start from a steady standing pose so the game can measure relative body movement.'],['Raise your body','Lift your shoulders and torso as a cactus approaches. Watch Dino rise over the camera view.'],['Return to standing','Settle back to your standing baseline before the next movement.']],[['stand','Stand in view'],['jump','Lift your shoulders'],['dino','Jump through your room']]),
 'orbit-pop':guide('Tap ten moving stars in this concept preview.','This preview uses pointer or touch input. It does not recognize body movements or open your camera.',[['Find the star','Look for the star in the play area.'],['Tap or click','Select the star with your finger or pointer. It moves after each hit.'],['Reach ten hits','Continue until the counter reaches ten, then start again.']],[['point','Use touch or pointer'],['target','Tap the star'],['target','Reach ten hits']],'This is a button-controlled concept, not a camera AR game.'),
};

// Only participating camera games require an entry gesture.
for(const [id,guide] of Object.entries(gameGuides)){if(!['orbit-pop','motion-quest','plank-flight','jump-game'].includes(id) && !guide.setup.includes('both hands'))guide.setup+=' When ready, raise both hands above your shoulders for one second, then lower them to start.';}
