import './style.css';
import {games} from './games.js';
import {drawPreview, setupPlayground, startConcept} from './playground.js';
import {mountRecording, renderLibrary, renderGallery, renderClip} from './recording.js';
const app=document.querySelector('#app');
const arrow='<span aria-hidden="true">↗</span>';
const nav=()=>`<a class="skip" href="#main">Skip to content</a><header class="nav"><a class="brand" href="/" aria-label="Fitness Pair home"><span class="brand-symbol" aria-hidden="true">↗</span>fitness pair</a><nav aria-label="Main navigation"><a href="/#arcade">The arcade</a><a href="/#why">Why movement games</a><a href="/#built">How we built it</a><a href="/gallery">The gallery</a></nav><a class="nav-play" href="/#arcade">Let’s play ${arrow}</a></header>`;
const footer=()=>`<footer class="footer"><a class="brand" href="/">↗ fitness pair</a><p>Get moving. Have fun.</p><div><a href="/library">My clips</a><a href="/gallery">Gallery</a><a href="/#built">Built with Astra</a></div></footer>`;
function home(){
app.innerHTML=`${nav()}<main id="main"><section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><p class="hero-note"><span class="live-dot"></span> Movement games for kids and adults</p><h1 id="hero-title">GAMES THAT GET<br><span>YOU MOVING.</span></h1><div class="hero-bottom"><p>Jump over cacti. Squat to cast spells.<br>Get active while you play.</p><a class="button primary hero-cta" href="#arcade">Take me to the arcade ${arrow}</a><p class="hero-aside">Use your camera.<br>Leave some room to move.</p></div></div><div class="playground" id="playground"><img src="/assets/playground.png" alt="A blue player and orange dinosaur leap through a bright floating playground." fetchpriority="high" width="1536" height="768"><canvas id="hero-motion" aria-hidden="true"></canvas><span id="landing-status" role="status"></span><button class="playground-poke" id="poke" aria-label="Launch a playground jump">Try a jump <span>↗</span></button><button class="motion-toggle" id="motion-toggle" aria-pressed="false">Pause motion</button><span class="scene-caption">Playground illustration · try the games below</span></div></section>
<section class="arcade-section section" id="arcade" aria-labelledby="arcade-title"><div class="section-head"><div><p class="kicker">The arcade</p><h2 id="arcade-title">PICK A GAME.<br><span>GET MOVING.</span></h2></div><p>Choose a game below.<br>Each one shows you how to play.</p></div><div class="game-grid">${games.map((g,i)=>`<article class="game-card ${g.color}"><a class="game-art" href="/play/${g.id}" aria-label="${g.kind==='concept'?'Try the concept':'Play'} ${g.title}"><canvas data-preview="${g.id}" width="720" height="480" role="img" aria-label="${g.title} illustrated game preview"></canvas><span class="game-status">${g.kind==='playable'?'Ready to play':'Concept preview'}</span><span class="launch" aria-hidden="true">↗</span></a><div class="game-info"><p class="game-meta">${g.label}</p><h3><a href="/play/${g.id}">${g.title}</a></h3><p>${g.action}</p><a class="text-link" href="/play/${g.id}">${g.kind==='concept'?'Try the concept':'Play now'} <span>→</span></a></div></article>`).join('')}</div><p class="arcade-footnote">For camera games, use a recent version of Chrome or Edge on a computer. You can also try keyboard controls before turning on your camera.</p></section>
<section class="why-section section" id="why"><div class="why-title"><p class="kicker">Why movement games</p><h2>MAKE TIME<br><span>FOR ACTIVE</span><br>PLAY.</h2><div class="spring-mark" aria-hidden="true">↗</div></div><div class="why-copy"><p class="lead">A fun way to fit more movement<br>into your day.</p><p>We’re building games for kids and adults who want to get up and move. Your camera follows your movements, so a squat can power a spell and a jump can clear an obstacle.</p><p>Play for a break from homework, between meetings, or whenever you feel like a game. The goal is simple: make physical activity something you look forward to.</p><a class="text-link" href="#arcade">Choose a game <span>→</span></a></div></section>
<section class="how-section section"><div class="section-head"><h2>READY IN<br>THREE STEPS.</h2><p>You need a camera<br>and space to move comfortably.</p></div><ol class="steps"><li><span>1</span><div><h3>Pick a game.</h3><p>Choose a game and clear enough room to move comfortably.</p></div></li><li><span>2</span><div><h3>Set up your camera.</h3><p>Turn on your camera and follow the setup steps so the game can recognise your movements. Tracking stays on your device.</p></div></li><li><span>3</span><div><h3>Start moving.</h3><p>Follow the game’s instructions and play at your own pace. Your camera turns off when you finish or leave.</p></div></li></ol></section>
<section class="built-section section" id="built"><div class="built-heading"><p class="kicker">How we built it</p><h2>BUILDING<br>THE ARCADE<br><span>WITH ASTRA.</span></h2><p>Our team builds the games.<br>Astra in Codex helps us design, code, and test.</p></div><div class="build-notes"><article><span class="note-tag">Design and code</span><h3>From an idea to a working page.</h3><p>We used Astra with the Impeccable design skill to try layouts, write the interface, and bring our games into one arcade. A separate agent generated the playground artwork while work on the page continued.</p></article><article><span class="note-tag">Movement controls</span><h3>How a movement becomes a game action.</h3><div class="pipeline"><span>Camera</span><b>→</b><span>Landmarks</span><b>→</b><span>Movement</span><b>→</b><span>Game</span></div><p>MediaPipe estimates body positions using your camera, on your device. Each game turns those positions into controls: completed squats in Motion Quest and changes in jump height in Dino Run.</p></article><article><span class="note-tag">Testing and iteration</span><h3>Build it, try it, improve it.</h3><p>Astra reads the code, makes changes, and runs automated checks. We can give feedback during a task, such as making the page bolder or making a game easier to find. We still need people to try the movement controls and tell us what works.</p><details><summary>A closer look at the build</summary><p>The build used parallel agent tasks for artwork, browser checks for the play and recording flows, and a separate design review. These checks help catch software and layout problems; they don’t tell us how accurately the camera recognises every player. <a class="text-link" href="https://developers.openai.com/api/docs/guides/latest-model" target="_blank" rel="noopener">Astra documentation ↗</a></p><p>Games share a common format for body positions and completed actions. That keeps tracking separate from game rules and helps prevent one movement from scoring twice. The arcade adds game selection and optional recording. Gallery uploads will use Google Cloud Storage once connected.</p><p>The games encourage movement; they don’t assess exercise technique or measure calories. Concept previews are labeled because their camera controls aren’t built yet.</p></details></article></div></section>
<section class="share-section section"><div class="share-art" aria-hidden="true"><div class="clip-shape"><span>WATCH<br>THAT<br>JUMP.</span><i>▶</i></div><span class="share-arrow">↗</span></div><div><p class="kicker">Your game clips</p><h2>SAVE YOUR<br><span>FAVORITE</span><br>MOMENTS.</h2><p>Choose to record a game, then watch or download your clip. Once gallery sharing is connected, you’ll be able to publish a clip and send friends its link.</p><a class="button dark" href="/gallery">Explore the gallery ${arrow}</a><p class="small-note">Your clips stay local until you choose to publish.<br>Gallery sharing isn’t available yet.</p></div></section>
<section class="final-invite"><p>Got a few minutes?</p><h2>LET’S PLAY.</h2><a class="button primary" href="#arcade">Take me to the arcade ${arrow}</a></section></main>${footer()}`;
document.querySelectorAll('[data-preview]').forEach(c=>drawPreview(c,c.dataset.preview));setupPlayground();
}
function play(id){
const g=games.find(g=>g.id===id);if(!g){app.innerHTML=`${nav()}<main id="main" class="utility"><h1>Game not found.</h1><a class="button primary" href="/#arcade">Back to the arcade →</a></main>${footer()}`;return;}
app.innerHTML=`${nav()}<main id="main" class="play-page"><div class="play-heading"><a class="back" href="/#arcade">← All games</a><h1>${g.title}</h1><p>${g.description}</p></div>${g.kind==='concept'?`<section class="concept-stage"><p class="concept-label">Interactive concept · button simulation · no camera</p><div class="concept-score"><strong id="pop-score">0</strong> / 10 pops</div><div id="pop-field"><button id="pop-target" aria-label="Pop the orbit">✳</button></div><p id="pop-status" role="status">Tap the star ten times. This preview uses buttons; camera controls are planned.</p><button class="button primary" id="pop-restart">Start again ↻</button></section>`:`<div class="record-bar" id="record-panel"></div><iframe id="game-frame" src="${g.path}" title="${g.title} game" allow="camera; fullscreen" referrerpolicy="same-origin"></iframe><section class="local-result" id="local-result" hidden></section>`}</main>${footer()}`;
if(g.kind==='concept')startConcept();else mountRecording(g,document.querySelector('#game-frame'));
}
const path=location.pathname;
if(path.startsWith('/play/'))play(path.split('/')[2]);
else if(path==='/library'||path==='/gallery'||path.startsWith('/clips/')){
app.innerHTML=`${nav()}<main class="utility section" id="main"><div id="content"></div></main>${footer()}`;
if(path==='/library')renderLibrary(document.querySelector('#content'));
else if(path==='/gallery')renderGallery(document.querySelector('#content'));
else renderClip(document.querySelector('#content'),path.split('/')[2]);
}else home();
