import './style.css';
import {games} from './games.js';
import {drawPreview, setupPlayground, startConcept} from './playground.js';
import {mountRecording, renderLibrary, renderGallery, renderClip} from './recording.js';
const app=document.querySelector('#app');
const arrow='<span aria-hidden="true">↗</span>';
const nav=()=>`<a class="skip" href="#main">Skip to content</a><header class="nav"><a class="brand" href="/" aria-label="Fitness Pair home"><span class="brand-symbol" aria-hidden="true">↗</span>fitness pair</a><nav aria-label="Main navigation"><a href="/#arcade">The arcade</a><a href="/#why">Why we play</a><a href="/#built">How we built it</a><a href="/gallery">The gallery</a></nav><a class="nav-play" href="/#arcade">Let’s play ${arrow}</a></header>`;
const footer=()=>`<footer class="footer"><a class="brand" href="/">↗ fitness pair</a><p>Made for the joy of moving.</p><div><a href="/library">My clips</a><a href="/gallery">Gallery</a><a href="/#built">Built with Astra</a></div></footer>`;
function home(){
app.innerHTML=`${nav()}<main id="main"><section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><p class="hero-note"><span class="live-dot"></span> Small games. Real movement.</p><h1 id="hero-title">YOUR BODY.<br><span>THE CONTROLLER.</span></h1><div class="hero-bottom"><p>Step away from the chair.<br>Step into a little adventure.</p><a class="button primary hero-cta" href="#arcade">Take me to the arcade ${arrow}</a><p class="hero-aside">Just you, your camera,<br>and a little room to move.</p></div></div><div class="playground" id="playground"><img src="/assets/playground.png" alt="A blue player and orange dinosaur leap through a bright floating playground." fetchpriority="high" width="1536" height="768"><canvas id="hero-motion" aria-hidden="true"></canvas><span id="landing-status" role="status"></span><button class="playground-poke" id="poke" aria-label="Launch a playground jump">Make a little jump <span>↗</span></button><button class="motion-toggle" id="motion-toggle" aria-pressed="false">Pause motion</button><span class="scene-caption">A little imagination. A lot of possibility.</span></div></section>
<section class="arcade-section section" id="arcade" aria-labelledby="arcade-title"><div class="section-head"><div><p class="kicker">Pick your next move</p><h2 id="arcade-title">LESS SCROLL.<br><span>MORE LET’S GO.</span></h2></div><p>Pick a world. Make some room.<br>Your first game is right here.</p></div><div class="game-grid">${games.map((g,i)=>`<article class="game-card ${g.color}"><a class="game-art" href="/play/${g.id}" aria-label="${g.kind==='concept'?'Try the concept':'Play'} ${g.title}"><canvas data-preview="${g.id}" width="720" height="480" role="img" aria-label="${g.title} illustrated game preview"></canvas><span class="game-status">${g.kind==='playable'?'Ready to play':'In the imagination lab'}</span><span class="launch" aria-hidden="true">↗</span></a><div class="game-info"><p class="game-meta">${g.label}</p><h3><a href="/play/${g.id}">${g.title}</a></h3><p>${g.action}</p><a class="text-link" href="/play/${g.id}">${g.kind==='concept'?'Try the concept':'Play now'} <span>→</span></a></div></article>`).join('')}</div><p class="arcade-footnote">Camera games work best in a recent desktop Chrome or Edge browser. There’s a button preview if you want a quick look.</p></section>
<section class="why-section section" id="why"><div class="why-title"><p class="kicker">Why we play</p><h2>SCREEN TIME.<br><span>WITH A LITTLE</span><br>SPRING IN IT.</h2><div class="spring-mark" aria-hidden="true">↗</div></div><div class="why-copy"><p class="lead">What if “one more game”<br>meant one more reason to move?</p><p>We’re building an arcade where your movements belong in the action. A squat becomes a spell. A hop takes a dinosaur over a cactus. Ordinary moves become tiny adventures.</p><p>No workout plan to keep up with. Just something fun to try, at your own pace. We’re exploring active play because moving should feel like an invitation.</p><a class="text-link" href="#arcade">Find your kind of play <span>→</span></a></div></section>
<section class="how-section section"><div class="section-head"><h2>YOUR ROOM.<br>NEW RULES.</h2><p>Three small steps.<br>A whole different way to play.</p></div><ol class="steps"><li><span>1</span><div><h3>Make a little space.</h3><p>Choose a game and clear enough room to move comfortably.</p></div></li><li><span>2</span><div><h3>Let the game see you.</h3><p>Enable your camera and follow the game’s calibration. Tracking runs on your device.</p></div></li><li><span>3</span><div><h3>See what your moves can do.</h3><p>Play at your own pace. Your camera turns off when you finish or leave.</p></div></li></ol></section>
<section class="built-section section" id="built"><div class="built-heading"><p class="kicker">Behind the play</p><h2>BIG IDEAS.<br>SMALL TEAM.<br><span>MEET ASTRA.</span></h2><p>Built by people, with Astra in Codex.<br>From a “what if” to something you can play.</p></div><div class="build-notes"><article><span class="note-tag">Imagine → make</span><h3>A creative coding partner.</h3><p>For this arcade, we used Astra with Impeccable to explore visual directions, build the interface, and connect independently developed games. Generated artwork sets the scene; code makes it respond.</p></article><article><span class="note-tag">See → move → play</span><h3>Your body speaks game.</h3><div class="pipeline"><span>Camera</span><b>→</b><span>Landmarks</span><b>→</b><span>Movement</span><b>→</b><span>Game</span></div><p>MediaPipe finds body landmarks locally. Each game’s recognizer turns calibrated movement into controls. Motion Quest counts completed squats; Dino Run explores relative jump height.</p></article><article><span class="note-tag">Build → check → learn</span><h3>Playful ideas. Checkable code.</h3><p>Astra helps inspect the code, implement interactions, and run automated checks. Simulations test the software loop. Real people still need to tell us how well it feels and plays.</p><details><summary>A closer look at the build</summary><p>Steering during the build let us refine the brief without restarting: bolder visuals, then a simpler path to play. A separate asset task produced the playground illustration while Astra continued the implementation. Browser checks and an independent design review helped catch issues before delivery. <a class="text-link" href="https://developers.openai.com/api/docs/guides/latest-model" target="_blank" rel="noopener">About Astra’s capabilities ↗</a></p><p>Independent game modules share named-joint data. Session IDs and explicit completion events keep repeated events from scoring twice. Camera resources are released on exit. This landing page adds game discovery, optional local clip recording, and a prepared GCP sharing gateway.</p><p>We don’t measure exercise quality, calories, or health outcomes. Upcoming concepts are labeled so you can explore without mistaking them for finished motion games.</p></details></article></div></section>
<section class="share-section section"><div class="share-art" aria-hidden="true"><div class="clip-shape"><span>THAT<br>WAS<br>A MOVE.</span><i>▶</i></div><span class="share-arrow">↗</span></div><div><p class="kicker">Good moves travel</p><h2>PLAY IT.<br>KEEP IT.<br><span>PASS IT ON.</span></h2><p>Record a little of your game if you want. Preview it on your device, then choose whether to share it with the gallery.</p><a class="button dark" href="/gallery">Explore the gallery ${arrow}</a><p class="small-note">Your clips stay local until you choose to publish.<br>Community publishing is being connected.</p></div></section>
<section class="final-invite"><p>Enough about play.</p><h2>YOUR MOVE.</h2><a class="button primary" href="#arcade">Take me to the arcade ${arrow}</a></section></main>${footer()}`;
document.querySelectorAll('[data-preview]').forEach(c=>drawPreview(c,c.dataset.preview));setupPlayground();
}
function play(id){
const g=games.find(g=>g.id===id);if(!g){app.innerHTML=`${nav()}<main id="main" class="utility"><h1>That game wandered off.</h1><a class="button primary" href="/#arcade">Back to the arcade →</a></main>${footer()}`;return;}
app.innerHTML=`${nav()}<main id="main" class="play-page"><div class="play-heading"><a class="back" href="/#arcade">← All games</a><h1>${g.title}</h1><p>${g.description}</p></div>${g.kind==='concept'?`<section class="concept-stage"><p class="concept-label">Interactive concept · button simulation · no camera</p><div class="concept-score"><strong id="pop-score">0</strong> / 10 pops</div><div id="pop-field"><button id="pop-target" aria-label="Pop the orbit">✳</button></div><p id="pop-status" role="status">Tap the star ten times. A future game could use reaching.</p><button class="button primary" id="pop-restart">Start again ↻</button></section>`:`<div class="record-bar" id="record-panel"></div><iframe id="game-frame" src="${g.path}" title="${g.title} game" allow="camera; fullscreen" referrerpolicy="same-origin"></iframe><section class="local-result" id="local-result" hidden></section>`}</main>${footer()}`;
if(g.kind==='concept')startConcept();else mountRecording(g,document.querySelector('#game-frame'));
}
const path=location.pathname;
if(path.startsWith('/play/'))play(path.split('/')[2]);
else if(path==='/library'||path==='/gallery'||path.startsWith('/clips/')){
app.innerHTML=`${nav()}<main class="utility section" id="main"><div id="content"></div></main>${footer()}`;
if(path==='/library')renderLibrary(document.querySelector('#content'));
else if(path==='/gallery')renderGallery(document.querySelector('#content'));
else renderClip(document.querySelector('#content'),path.split('/')[2]);
}else home();
