import {controlProfiles} from '../../packages/gameplay/control-profiles.js';
// Shared registration data for the UI, build and publication allowlist.
export const gameCatalog = [
  {"id": "ar-breakout", "section": "other", "directory": "apps/integ-ar", "title": "Brick Pulse AR", "action": "Move your torso left and right to guide the paddle.", "label": "Paddle arcade · camera AR", "kind": "playable", "color": "forest", "poster": "MOVE.<br>BOUNCE.", "path": "/games/ar-breakout/?game=breakout", "description": "Move your torso left and right to guide the paddle. Calibrate your torso, then play over your camera with live body tracking."},
  {"id": "ar-invaders", "section": "other", "directory": "apps/integ-ar", "title": "Pixel Defense AR", "action": "Move your torso to steer. Raise your left hand to fire.", "label": "Space shooter · camera AR", "kind": "playable", "color": "orbit", "poster": "MOVE.<br>DEFEND.", "path": "/games/ar-invaders/?game=invaders", "description": "Move your torso to steer. Raise your left hand to fire. Calibrate your torso, then play over your camera with live body tracking."},
  {"id": "ar-stack", "section": "other", "directory": "apps/integ-ar", "title": "Perfect Stack AR", "action": "Raise your left hand when the moving slab lines up.", "label": "Timing & building · camera AR", "kind": "playable", "color": "desert", "poster": "RAISE.<br>STACK.", "path": "/games/ar-stack/?game=stack", "description": "Raise your left hand when the moving slab lines up. Calibrate your torso, then play over your camera with live body tracking."},
  {"id": "ar-knife", "section": "other", "directory": "apps/integ-ar", "title": "Orbit Knife AR", "action": "Raise your left hand to throw into a clear space.", "label": "Timing & throwing · camera AR", "kind": "playable", "color": "orbit", "poster": "RAISE.<br>THROW.", "path": "/games/ar-knife/?game=knife", "description": "Raise your left hand to throw into a clear space. Calibrate your torso, then play over your camera with live body tracking."},
  {"id": "ar-bubble", "section": "other", "directory": "apps/integ-ar", "title": "Bubble Pop AR", "action": "Aim with your right wrist below shoulder height. Raise your left hand to shoot.", "label": "Aim & match · camera AR", "kind": "playable", "color": "forest", "poster": "AIM.<br>POP.", "path": "/games/ar-bubble/?game=bubble", "description": "Aim with your right wrist below shoulder height. Raise your left hand to shoot. Calibrate your torso, then play over your camera with live body tracking."},
  {"id": "ar-fruit", "section": "other", "directory": "apps/integ-ar", "title": "Fruit Orbit AR", "action": "Move your torso to aim. Raise your left hand to drop fruit.", "label": "Physics & merging · camera AR", "kind": "playable", "color": "desert", "poster": "MOVE.<br>MERGE.", "path": "/games/ar-fruit/?game=fruit-merge", "description": "Move your torso to aim. Raise your left hand to drop fruit. Calibrate your torso, then play over your camera with live body tracking."},
  {id:'motion-quest', section:'feature', directory:'apps/motion-quest', adapter:'motionQuestAdapter', title:'Motion Quest', action:'Squat to charge a spell. Stand to cast it.', label:'Camera · five squats', kind:'playable', color:'forest', path:'/games/motion-quest/', description:'Stand tall to calibrate. Squat to charge and stand to cast. Repel five approaching guardians to clear the wave.'},
  {id:'plank-flight', section:'feature', directory:'experiments/gameplay/plank-flight', adapter:'plankFlightAdapter', title:'Push-up Flight', action:'Move your head to fly a tiny helicopter.', label:'Camera or pointer demo · experimental', kind:'playable', color:'orbit', path:'/games/plank-flight/', description:'Your head guides the helicopter. Lower down and push up to move through gates, or try the pointer demo. Set a pace that feels comfortable.'},
  {id:'jump-game', section:'feature', aliases:['camera-start'], directory:'apps/camera-start', adapter:'cameraStartAdapter', title:'Jump Game', action:'Stand, confirm, then jump over cacti.', label:'Camera · guided setup · experimental', kind:'playable', color:'forest', preview:'jump-game', path:'/games/jump-game/', description:'Stand still to calibrate, confirm, and follow the countdown into the run. Jump to clear the cacti.'},
  {id:'orbit-pop', section:'other', title:'Orbit Pop', action:'Tap moving targets in this concept preview.', label:'Interactive concept · no camera', kind:'concept', color:'orbit', description:'Tap ten moving targets. This is a button-controlled preview of a planned reaching game; it does not use your camera.'}
].map(game=>({...game,controlProfile:controlProfiles[game.id]}));

export const playableGames=gameCatalog.filter(game=>game.kind==='playable');
export const isPlayableGame=id=>playableGames.some(game=>game.id===id||game.aliases?.includes(id));

// Saved clips retain their original game IDs after prototype retirement.
export const isRecordingGame=id=>isPlayableGame(id)||['dino-run','dino-ar'].includes(id);
