// Shared registration data for the UI, build and publication allowlist.
export const gameCatalog = [
  {id:'motion-quest', directory:'apps/motion-quest', adapter:'motionQuestAdapter', title:'Motion Quest', action:'Squat to charge a spell. Stand to cast it.', label:'Camera · five squats', kind:'playable', color:'forest', path:'/games/motion-quest/', description:'Stand tall to calibrate. Squat to charge and stand to attack. Complete five squats to finish the round.'},
  {id:'dino-run', recordingControlPosition:{top:'70px',bottom:'auto'}, directory:'apps/dino-run', listed:false, title:'Dino Run', action:'Jump to help Dino clear the cacti.', label:'Camera · jump-height experiment', kind:'playable', color:'desert', path:'/games/dino-run/', description:'Set your standing pose and a comfortable jump range, then jump to move Dino over obstacles. You can also play with your keyboard.'},
  {id:'dino-ar', recordingControlPosition:{bottom:'60px'}, directory:'experiments/gameplay/dino-ar', adapter:'dinoARAdapter', listed:false, title:'Dino AR', action:'Lift your body to help Dino jump through your room.', label:'Camera or keyboard · experimental', kind:'playable', color:'desert', preview:'dino-run', path:'/games/dino-ar/', description:'Dino plays over your camera view. Lift your shoulders to jump, or choose keyboard mode to try the game first.'},
  {id:'plank-flight', recordingControlPosition:{top:'122px',bottom:'auto'}, directory:'experiments/gameplay/plank-flight', adapter:'plankFlightAdapter', title:'Push-up Flight', action:'Move your head to fly a tiny helicopter.', label:'Camera or pointer demo · experimental', kind:'playable', color:'orbit', poster:'HEAD IN<br>THE GAME.', path:'/games/plank-flight/', description:'Your head guides the helicopter. Lower down and push up to move through gates, or try the pointer demo. Set a pace that feels comfortable.'},
  {id:'camera-start', recordingControlPosition:{top:'140px',bottom:'auto'}, directory:'apps/camera-start', adapter:'cameraStartAdapter', title:'Ready to Move', action:'Set your movement range, then jump over cacti.', label:'Camera · guided setup · experimental', kind:'playable', color:'forest', preview:'dino-run', path:'/games/camera-start/', description:'Follow the standing setup, choose a comfortable movement range, and start a Dino run. This version guides you through camera setup one step at a time.'},
  {id:'orbit-pop', listed:false, title:'Orbit Pop', action:'Tap moving targets in this concept preview.', label:'Interactive concept · no camera', kind:'concept', color:'orbit', description:'Tap ten moving targets. This is a button-controlled preview of a planned reaching game; it does not use your camera.'}
];

export const playableGames=gameCatalog.filter(game=>game.kind==='playable');
export const isPlayableGame=id=>playableGames.some(game=>game.id===id);
