// Adapted from flyfy1/integ-games c2a3374; see apps/integ-ar/README.md.
import type { GameController, GameModule, GameServices } from '../../core/game-types';
import { clamp, makeKit, text, clayRect, clayShip } from '../arcade-kit';

type Foe = { x: number; y: number; alive: boolean };
type Shot = { x: number; y: number };

export const invaders: GameModule = { meta: { slug: 'invaders', title: 'Pixel Defense', category: 'action', description: 'Defend the signal beacon from advancing pixel swarms.', instructions: 'Move with arrows or drag; tap or Space fires.', accent: '#8b7cff', mechanic: 'Shoot waves and dodge fire' }, mount(host: HTMLElement, services: GameServices): GameController {
  const k = makeKit(host, services, 'invaders'); let raf = 0, paused = false, over = false, score = 0, wave = 1, ship = 160, direction = 1, frames = 0, shotsFired = 0;
  let shots: Shot[] = [], enemyShots: Shot[] = [], foes: Foe[] = [];
  const spawn = () => { foes = []; for (let row = 0; row < 4; row++) for (let col = 0; col < 7; col++) foes.push({ x: 44 + col * 42, y: 75 + row * 32, alive: true }); };
  const reset = () => { paused = false; over = false; score = 0; wave = 1; ship = 160; direction = 1; frames = 0; shotsFired = 0; shots = []; enemyShots = []; k.fx.clear(); spawn(); }; reset();
  const fire = () => { if (!paused && !over && shots.length < 3) { shotsFired++; shots.push({ x: ship + 20, y: 470 }); k.fx.burst(ship + 20, 482, '#70f0c2', 4); services.sound.play('shoot'); } }; k.on('pointermove', event => { ship = clamp(k.point(event as PointerEvent).x - 20, 8, 312); }); k.on('pointerdown', () => over ? reset() : fire()); k.on('keydown', event => { if ((event as KeyboardEvent).key === ' ') over ? reset() : fire(); });
  const draw = () => { const c = k.ctx; k.clear();  text(c, `SCORE ${score}  WAVE ${wave}`, 180, 28, 15, '#a8b1c5'); clayShip(c,ship,484,40,20); foes.filter(foe => foe.alive).forEach(foe => { clayRect(c,foe.x,foe.y,24,16,'#a1b879',7); c.fillStyle = '#243f61'; for(const eye of [6,18]){c.beginPath();c.ellipse(foe.x+eye,foe.y+7,2,3,0,0,Math.PI*2);c.fill();} }); c.fillStyle = '#70f0c2'; shots.forEach(shot => clayRect(c,shot.x,shot.y,3,12,'#85d7c8',1)); c.fillStyle = '#ff6b7a'; enemyShots.forEach(shot => clayRect(c,shot.x,shot.y,3,10,'#e88e72',1)); k.fx.draw(); if (paused) text(c, 'PAUSED', 180, 280, 27, '#fff8e9'); if (over) { text(c, 'BEACON DOWN', 180, 260, 25, '#ff6b7a'); text(c, 'Finish or start a new round', 180, 290, 15, '#fff8e9'); } };
  let lastStep = performance.now(); const loop = (now = lastStep) => { if (now - lastStep < 1000 / 60 - .1) { raf = requestAnimationFrame(loop); return; } lastStep = now - (now - lastStep) % (1000 / 60); if (!paused && !over) { frames++; if (k.keys.has('ArrowLeft') || k.keys.has('a')) ship = clamp(ship - 5, 8, 312); if (k.keys.has('ArrowRight') || k.keys.has('d')) ship = clamp(ship + 5, 8, 312); const cadence = Math.max(5, 20 - wave); if (frames % cadence === 0) { let edge = false; foes.filter(foe => foe.alive).forEach(foe => { foe.x += direction * (1 + wave * .12); if (foe.x < 8 || foe.x > 328) edge = true; }); if (edge) { direction *= -1; foes.forEach(foe => { foe.y += 12; }); } const live = foes.filter(foe => foe.alive); if (live.length) { const foe = live[Math.floor(services.random() * live.length)]; enemyShots.push({ x: foe.x + 12, y: foe.y + 16 }); } }
    shots.forEach(shot => { shot.y -= 8; }); enemyShots.forEach(shot => { shot.y += 3 + wave * .25; }); shots = shots.filter(shot => shot.y > 40); enemyShots = enemyShots.filter(shot => shot.y < 520); for (const shot of shots) for (const foe of foes) if (foe.alive && shot.x > foe.x && shot.x < foe.x + 24 && shot.y > foe.y && shot.y < foe.y + 18) { foe.alive = false; shot.y = -20; score += 10; k.score(score); k.fx.burst(foe.x + 12, foe.y + 8, '#ff6b7a'); services.sound.play('hit'); }
    if (enemyShots.some(shot => shot.x > ship && shot.x < ship + 40 && shot.y > 480) || foes.some(foe => foe.alive && foe.y > 450)) { over = true; k.fx.flash('#ff6b7a'); services.sound.play('fail'); } if (!foes.some(foe => foe.alive)) { wave++; score += 50; k.score(score); services.reportComplete(wave); spawn(); k.fx.flash('#8b7cff'); services.sound.play('clear'); } k.fx.step(); } draw(); raf = requestAnimationFrame(loop); };
  loop(); return { input: command => { if (!paused && !over) { ship = 8 + (command.horizontal + 1) * 152; if (command.primary) fire(); } }, getState: () => ({phase: over ? 'lost' : paused ? 'paused' : 'playing', score, wave, ship, shots: shots.map(shot => ({...shot})), shotsFired}), pause: () => { paused = true; }, resume: () => { paused = false; }, restart: reset, destroy: () => { cancelAnimationFrame(raf); k.dispose(); } };
} };
export default invaders;
