import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {createPlayStats} from './play-stats.mjs';
const origin='https://fitness.test',games=[{id:'one',title:'One'},{id:'two',title:'Two'}];
async function fixture(t){const directory=await mkdtemp(tmpdir()+'/play-stats-');t.after(()=>rm(directory,{recursive:true,force:true}));let time=Date.now();const options={directory,origin,games,adminEmails:'owner@example.test',now:()=>time,getUser:async req=>req.headers.get('X-Test-User')==='admin'?{email:'owner@example.test',userId:'account1'}:req.headers.get('X-Test-User')==='other'?{email:'other@example.test',userId:'account2'}:null};let store=createPlayStats(options);return {directory,restart(){store=createPlayStats(options);},advance(ms){time+=ms;},body(extra={}){return {version:1,id:randomUUID(),playerId:randomUUID(),gameId:'one',sequence:1,startedAt:time,updatedAt:time,activeMs:0,inputSource:'camera',endReason:null,...extra};},send(body,headers={}){return store.handle(new Request(origin+'/api/play-sessions',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',...headers},body:JSON.stringify(body)}));},report(query='',user='admin'){return store.handle(new Request(origin+'/api/admin/game-stats'+query,{headers:user?{'X-Test-User':user}:{}}));}};}
test('rounds survive restart, deduplicate players and retries, report exact times and all games',async t=>{const f=await fixture(t),a=f.body();await f.send(a);f.advance(5000);const final={...a,sequence:3,updatedAt:a.startedAt+5000,activeMs:3500,endReason:'completed'};await f.send(final);await f.send(final);await f.send({...a,sequence:2,updatedAt:a.startedAt+1000,activeMs:1000});await f.send(f.body({playerId:a.playerId}));f.restart();const result=await (await f.report()).json();assert.equal(result.total,2);assert.deepEqual(result.summary,[{gameId:'one',title:'One',players:1,sessions:2,activeMs:3500},{gameId:'two',title:'Two',players:0,sessions:0,activeMs:0}]);const row=result.sessions.find(r=>r.id===a.id);assert.equal(row.endedAt,final.updatedAt);assert.equal(row.activeMs,3500);assert.equal(row.status,'completed');assert.equal(row.deviceId,undefined);assert.equal(row.email,undefined);assert.notEqual(row.playerId,a.playerId);assert.equal((await readdir(f.directory+'/play-sessions')).length,1);});
test('admin access fails closed, invalid origin/body/timestamps/ownership cannot write',async t=>{const f=await fixture(t),a=f.body();assert.equal((await f.report('',null)).status,401);assert.equal((await f.report('','other')).status,403);await assert.rejects(f.send(a,{Origin:'https://attacker.test'}),{status:403});await assert.rejects(f.send({...a,gameId:'missing'}),{status:400});await assert.rejects(f.send({...a,activeMs:9000}),{status:400});await assert.rejects(f.send({...a,padding:'x'.repeat(3000)}),{status:413});await f.send(a);await assert.rejects(f.send({...a,sequence:2,playerId:randomUUID()}),{status:409});await assert.rejects(f.report('?from=2026-01-01&to=2026-03-01'),{status:400});});
test('account deduplication, source filters, interruption and pagination',async t=>{const f=await fixture(t);for(let i=0;i<102;i++)await f.send(f.body({inputSource:i===0?'synthetic':'camera'}),{'X-Test-User':'admin'});f.advance(46000);const all=await (await f.report()).json();assert.equal(all.summary[0].players,1);assert.equal(all.sessions.length,100);assert.equal(all.nextOffset,100);assert.equal(all.sessions[0].status,'interrupted');assert.equal(all.sessions[0].endedAt,null);assert.equal((await (await f.report('?offset=100')).json()).sessions.length,2);assert.equal((await (await f.report('?source=synthetic')).json()).total,1);assert.equal((await (await f.report('?game=two')).json()).total,0);});
